name: Build HivotDev
on:
  push:
    branches:
      - main
   
jobs:
  build:
    runs-on: macos-12
    steps:
    - name: ios version
      run: sw_vers
    - name: xcode version
      run: xcodebuild -version
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.4.1'
    
    - name: check
      run: xcodebuild -version
