name: Build HivotDev
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Building iOS App
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - name: Install xcode-install
        env:
          FASTLANE_USER: ${{ secrets.APPLE_USERNAMEE }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_PASS }}
        run: |
          gem install fastlane
          fastlane spaceship
          sudo gem install xcode-install -v 2.7.0
          xcversion install 13.4.1
    
      - name: check
        run: xcodebuild -version