name: Build HivotDev
on:
  push:
    branches:
      - main
   
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.4.1'
    
      - name: check
        run: xcodebuild -version
