name: Build HivotDev
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Building iOS App
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - name: Install xcode-install
        env:
          FASTLANE_USER: ${{ secrets.APPLE_USERNAME }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_PASS }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_SPEC_PASS }}
          SPACESHIP_ONLY_ALLOW_INTERACTIVE_2FA: True
        run: |
          sudo gem install fastlane
          # fastlane spaceauth -u $FASTLANE_USER
          sudo gem install spaceship
          gem install pry
          fastlane spaceship
          fastlane scan
          sudo gem install xcode-install
          xcversion install 13.4.1
    
      - name: check
        run: xcodebuild -version